version: "3.7"

services:
  admin:
    restart: always
    container_name: dssaude_site
    ports:
      - 127.0.0.1:${NEXT_PORT}:3000
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile